feast-core:
  # feast-core.enabled -- Flag to install Feast Core
  enabled: true
  postgresql:
    # feast-core.postgresql.existingSecret -- Kubernetes secrets that contains the postgresql password
    existingSecret: feast-postgresql

feast-online-serving:
  # feast-online-serving.enabled -- Flag to install Feast Online Serving
  enabled: true

feast-jupyter:
  # feast-jupyter.enabled -- Flag to install Feast Jupyter Notebook with SDK
  enabled: false

feast-jobservice:
  # feast-jobservice.enabled -- Flag to install Feast Job Service
  enabled: true

postgresql:
  # postgresql.enabled -- Flag to install Postgresql
  enabled: true
  # postgresql.existingSecret -- Kubernetes secrets that contains the postgresql password
  existingSecret: feast-postgresql

kafka:
  # kafka.enabled -- Flag to install Kafka
  enabled: false

redis:
  # redis.enabled -- Flag to install Redis
  enabled: true
  # redis.usePassword -- Disable redis password
  usePassword: false

prometheus-statsd-exporter:
  # prometheus-statsd-exporter.enabled -- Flag to install StatsD to Prometheus Exporter
  enabled: false

prometheus:
  # prometheus.enabled -- Flag to install Prometheus
  enabled: false

grafana:
  # grafana.enabled -- Flag to install Grafana
  enabled: false
